# Generated by Django 3.1.5 on 2021-01-18 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bicycles', '0002_auto_20210114_0528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marks',
            options={'ordering': ['mark'], 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.RemoveField(
            model_name='bsles',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bsles',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='bsles',
            name='reservation',
        ),
        migrations.AlterField(
            model_name='bsles',
            name='stamp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Bicycles.marks', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='bsles',
            name='wheels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Bicycles.wheels', verbose_name='Колеса'),
        ),
        migrations.DeleteModel(
            name='Frame',
        ),
    ]
